generate_text:
  name: Generate Text
  description: Generate text using DeepSeek AI.
  target: {}
  fields:
    prompt:
      name: Prompt
      description: The prompt to send to DeepSeek.
      required: true
      example: "Write a short poem about home automation."
      selector:
        text:
          multiline: true
  response_variable:
    description: The response from DeepSeek
    example: >
      response_variable: deepseek_response